### ISSUE TITLE
无法添加服务器

### ISSUE THREAD

**Issue by Typmn** [jie65535/JGrasscutterCommand#20]
![Screenshot_20221106_154938](https://user-images.githubusercontent.com/103867786/200159931-216aee77-6115-47e2-a579-58874f33c038.jpg)
![Screenshot_20221106_155027](https://user-images.githubusercontent.com/103867786/200159959-1fe42faa-b3da-4752-8d69-f627f1deac56.jpg)
问题是我已经安装了的也开启了

**Comment by jie65535** [comment]
将日志中的完整异常信息发出来，那句话是通用错误回复，需要日志中的异常信息才能定位具体问题。

**Comment by Typmn** [comment]
在那个文件夹里

**Comment by jie65535** [comment]
目录下的logs文件夹，或者你直接从控制台里将相关的信息复制也行。

我建议你首先检查设置的参数是否正确，你可以使用浏览器访问确认，注意端口号要正确。

**Comment by Typmn** [comment]
> [已删除大段无用信息]

```log
2022-11-06 16:32:42 W/J Grasscutter Command: ping ***.**.**.*** 异常
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1260)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1633)
	at okhttp3.Request$Builder.url(Request.kt:184)
	at JGrasscutterCommand-0.4.0.mirai2.jar//top.jie65535.mirai.opencommand.OpenCommandApi.doRequest(OpenCommandApi.kt:91)
	at JGrasscutterCommand-0.4.0.mirai2.jar//top.jie65535.mirai.opencommand.OpenCommandApi.ping(OpenCommandApi.kt:117)
	at JGrasscutterCommand-0.4.0.mirai2.jar//top.jie65535.mirai.PluginCommands.tryPing(PluginCommands.kt:144)
	at JGrasscutterCommand-0.4.0.mirai2.jar//top.jie65535.mirai.PluginCommands.addServer(PluginCommands.kt:161)
	at JGrasscutterCommand-0.4.0.mirai2.jar//top.jie65535.mirai.PluginCommands.addServer$default(PluginCommands.kt:154)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)
	at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:337)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
	at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:167)
	at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:130)
	at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
	at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:187)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by jie65535** [comment]
> Expected URL scheme 'http' or 'https' but no colon was found

你的地址要包含`http`或者`https`的开头，而且注意你的端口号如果有改变也必须指定。

**Comment by Typmn** [comment]
我试试

**Comment by Typmn** [comment]
好了谢谢，
