### ISSUE TITLE
[兼容性问题] 无法添加服务器

### ISSUE THREAD

**Issue by azhegod** [jie65535/JGrasscutterCommand#5]
2022-09-18 11:58:39 I/J Grasscutter Command 正在 ping https://117.50.186.115:520122022-09-18 11:58:39 W/J Grasscutter Command ping https://117.50.186.115:52012 异常
java.lang.NoClassDefFoundError: kotlinx/serialization/json/JvmStreamsKt
	at top.jie65535.mirai.opencommand.OpenCommandApi$doRequest$2.invokeSuspend(OpenCommandApi.kt:187)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-09-18 11:58:39 I/compose 只能设置装有 [OpenCommand](https://github.com/jie65535/gc-opencommand-plugin) 插件的服务器

**Comment by jie65535** [comment]
经过私下沟通，该问题是由于使用了Mirai用户手册中的GUI运行插件导致，GUI使用的Mirai版本为2.9.2，当前Mirai最新版本是2.12.2，因此产生的兼容性问题。

若你遇到相同问题，请使用Mirai控制台版本，直到GUI发布新版。
